routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\CategoriaTipoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('categoria/showView/{categoria}', [CategoriaController::class, 'showView']);
//Route::get('categoria/{categoria}/edit', [CategoriaController::class, 'edit']);
Route::resource('categorias', CategoriaController::class);
Route::get('categorias/{categoria}', [CategoriaController::class, 'destroy'])->name('categorias.delete');

Route::resource('categoria_tipos', CategoriaTipoController::class);
Route::get('categoria_tipos/{categoria_tipo}', [CategoriaTipoController::class, 'destroy'])->name('categoria_tipos.delete');

app/Models/Categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Categoria extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $fillable = ['nome'];
}

app/Models/CategoriaTipo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CategoriaTipo extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $fillable = ['nome', 'descrizione'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categoria;
use Illuminate\Http\Request;

class CategoriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('categorias.index', ['categorie'=> Categoria::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('categorias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $categoria = new Categoria($request->all());
        $categoria->save();
        return view('categorias.index', ['categorie'=> Categoria::all()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Categoria  $categoria
     * @return \Illuminate\Http\Response
     */
    public function show(Categoria $categoria)
    {
        //
        return view('categorias.show', ['categoria'=> $categoria]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Categoria  $categoria
     * @return \Illuminate\Http\Response
     */
    public function edit(Categoria $categoria)
    {
        //
        return view('categorias.edit', ['categoria'=> $categoria]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Categoria  $categoria
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categoria $categoria)
    {
        //
        $categoria->fill($request->all());
        $categoria->save();
        return view('categorias.index', ['categorie'=> Categoria::all()]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Categoria  $categoria
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categoria $categoria)
    {
        //
        $categoria->delete();
        return view('categorias.index', ['categorie'=> Categoria::all()]);

    }
}

app/Http/Controllers/CategoriaTipoController.php
<?php

namespace App\Http\Controllers;

use App\Models\CategoriaTipo;
use Illuminate\Http\Request;

class CategoriaTipoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('categoria_tipos.index', ['categoria_tipi'=> CategoriaTipo::all()]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categoria_tipos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tipo_categoria = new CategoriaTipo($request->all());
        $tipo_categoria->save();
        return view('categoria_tipos.index', ['categoria_tipi'=> CategoriaTipo::all()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\CategoriaTipo  $categoriaTipo
     * @return \Illuminate\Http\Response
     */
    public function show(CategoriaTipo $categoriaTipo)
    {
        //
        return view('categoria_tipos.show', ['categoria_tipo'=> $categoriaTipo]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\CategoriaTipo  $categoriaTipo
     * @return \Illuminate\Http\Response
     */
    public function edit(CategoriaTipo $categoriaTipo)
    {
        //
        return view('categoria_tipos.edit', ['categoria_tipo'=> $categoriaTipo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\CategoriaTipo  $categoriaTipo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CategoriaTipo $categoriaTipo)
    {
        //
        $categoriaTipo->fill($request->all());
        $categoriaTipo->save();
        return view('categoria_tipos.index', ['categoria_tipi'=> CategoriaTipo::all()]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\CategoriaTipo  $categoriaTipo
     * @return \Illuminate\Http\Response
     */
    public function destroy(CategoriaTipo $categoriaTipo)
    {
        //
        $categoriaTipo->delete();
        return view('categoria_tipos.index', ['categoria_tipi'=> CategoriaTipo::all()]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/categoria_tipos/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <style>
        input[type=text] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>
</head>
<body>

<p>Text fields with borders:</p>

<form action="{{ route('categoria_tipos.store') }}" method="post">
    {{ csrf_field() }}
    @method('POST')
    <input type="text" name="nome" placeholder="Tipo Categoria" required>
    <input type="text" name="descrizione" placeholder="Descrizione Tipo Categoria" >
    <button type="submit" class="btn btn-danger">Crea</button>
</form>

</body>
</html>

resources/views/categoria_tipos/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <style>
        input[type=text] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>
</head>
<body>

<p>Text fields with borders:</p>

<form action="{{route('categoria_tipos.update', $categoria_tipo->id)}}" method="post">
    {{ csrf_field() }}
    @method('PUT')
    <input type="text" name="nome" placeholder="Nome" value="{{strtoupper($categoria_tipo->nome)}}" required>
    <input type="text" name="descrizione" placeholder="Descrizione" value="{{$categoria_tipo->descrizione}}" >
    <button type="submit" class="btn btn-danger">Aggiorna</button>
</form>

</body>
</html>

resources/views/categoria_tipos/index.blade.php
<!DOCTYPE html>
<html>
<head>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
PIPPO
{{$categoria_tipi}}
<h2>Tipi Categorie</h2>

<a href="{{route('categoria_tipos.create')}}">
    <img src="https://img.icons8.com/cute-clipart/30/000000/new.png"/>
</a>

<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Description</th>
        <th>Actions</th>
    </tr>
    @if (count($categoria_tipi) >= 1)
        @foreach ($categoria_tipi as $categoria_tipo)
            <tr>
                <td style="width: 10%">{{$categoria_tipo->id}}</td>
                <td style="width: 20%">{{strtoupper($categoria_tipo->nome)}}</td>
                <td style="width: 50%">{{$categoria_tipo->descrizione}}</td>
                <td>
                    <a href="{{route('categoria_tipos.edit', $categoria_tipo->id)}}">
                        <img src="https://img.icons8.com/wired/30/000000/edit.png" alt="Picture Description">
                    </a>
                    <a href="{{route('categoria_tipos.show', $categoria_tipo->id)}}">
                        <img src="https://img.icons8.com/wired/30/000000/show-property.png" alt="Picture Description">
                    </a>
                    <a href="{{route('categoria_tipos.delete', $categoria_tipo->id)}}">
                        <img src="https://img.icons8.com/wired/30/000000/delete-forever.png" alt="Picture Description">
                    </a>
                </td>
            </tr>
        @endforeach
    @else
        <tr>
            <td colspan="4" style="text-align: center">No records</td>
        </tr>
    @endif

</table>

</body>
</html>

resources/views/categoria_tipos/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <style>
        input[type=text] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>
</head>
<body>

<p>Text fields with borders:</p>

<form>
    <input type="text" name="nome" value="{{$categoria_tipo->nome}}" placeholder="Tipo Categoria" required readonly>
    <input type="text" name="descrizione" value="{{$categoria_tipo->descrizione}}" placeholder="Descriziolne Tipo Categoria" required readonly>
</form>

</body>
</html>

resources/views/categorias/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <style>
        input[type=text] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>
</head>
<body>

<p>Text fields with borders:</p>

<form action="{{ route('categorias.store') }}" method="post">
    {{ csrf_field() }}
    @method('POST')
    <input type="text" name="nome" placeholder="Nome Categoria" required>
    <button type="submit" class="btn btn-danger">Crea</button>
</form>

</body>
</html>

resources/views/categorias/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <style>
        input[type=text] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>
</head>
<body>

<p>Text fields with borders:</p>

<form action="{{route('categorias.update', $categoria->id)}}" method="post">
    {{ csrf_field() }}
    @method('PUT')
    <input type="text" name="nome" placeholder="Email Address" value="{{strtoupper($categoria->nome)}}" required>
    <button type="submit" class="btn btn-danger">Aggiorna</button>
</form>

</body>
</html>

resources/views/categorias/index.blade.php
<!DOCTYPE html>
<html>
<head>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
PIPPO
{{$categorie}}
<h2>Categorie</h2>

<a href="{{route('categorias.create')}}">
    <img src="https://img.icons8.com/cute-clipart/30/000000/new.png"/>
</a>

<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Actions</th>
    </tr>
    @if (count($categorie) >= 1)
        @foreach ($categorie as $categoria)
            <tr>
                <td style="width: 10%">{{$categoria->id}}</td>
                <td style="width: 70%">{{strtoupper($categoria->nome)}}</td>
                <td>
                    <a href="{{route('categorias.edit', $categoria->id)}}">
                        <img src="https://img.icons8.com/wired/30/000000/edit.png" alt="Picture Description">
                    </a>
                    <a href="{{route('categorias.show', $categoria->id)}}">
                        <img src="https://img.icons8.com/wired/30/000000/show-property.png" alt="Picture Description">
                    </a>
                    <a href="{{route('categorias.delete', $categoria->id)}}">
                        <img src="https://img.icons8.com/wired/30/000000/delete-forever.png" alt="Picture Description">
                    </a>
                </td>
            </tr>
        @endforeach
    @else
        <tr>
            <td colspan="3" style="text-align: center">No records</td>
        </tr>
    @endif

</table>

</body>
</html>

resources/views/categorias/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <style>
        input[type=text] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>
</head>
<body>

<p>Text fields with borders:</p>

<form>
    <input type="text" name="nome" value="{{$categoria->nome}}" placeholder="Nome Categoria" required readonly>
</form>

</body>
</html>